### ISSUE TITLE
Support Custom Types for Lists

### ISSUE THREAD

**Issue by gabosgab** [hsgubert/cassandra_migrations#73]
Currently, it looks like the create_table action does not support custom types.

### Schema
```
execute('DROP TYPE IF EXISTS action');
    execute('
      CREATE TYPE
       action(
        created_at timestamp,
        secondary_entity_id int,
        action_id int,
        verb_id int
       );
    ')

    create_table :activities,
               partition_keys: [:user_id, :created_at, :entity_id],
               primary_keys:   [:user_id, :created_at, :entity_id] do |t|
      t.integer   :created_at
      t.integer   :user_id
      t.integer   :entity_id
      t.list      :actions, :type => 'action'
    end
```

### Migration Error
> CassandraMigrations::Errors::MigrationDefinitionError: Type 'action' is not valid for cassandra migration.
/Users/gabe/.rvm/gems/ruby-2.2.1/gems/cassandra_migrations-0.2.5/lib/cassandra_migrations/migration/table_definition.rb:290:in `list_or_set'
/Users/gabe/.rvm/gems/ruby-2.2.1/gems/cassandra_migrations-0.2.5/lib/cassandra_migrations/migration/table_definition.rb:166:in `list'
/Users/gabe/src/stolenapi/db/cassandra_migrate/20160118193215_activty_feed.rb:21:in `block in up'

**Comment by ckhall** [comment]
:+1:
